### ISSUE TITLE
Best theme by far

### ISSUE THREAD

**Issue by maxkerp** [mrliptontea/PurpleMine2#105]
This is the best redmine theme by far. It's the only theme I found which is frequently updated and works nicely with redmine 4.0. Kudos and thank you a lot! :+1: 

Adding to that, I really like that it feels a bit like gitlab. If you need feedback or help, don't hesitate to ask me. Although I would not consider myself to be proficient in `scss`, I could see me level up on that for this project :sweat_smile:

**Comment by mrliptontea** [comment]
Hi,
Thanks for the kind words!

I don't use Redmine professionally anymore, last few changes I made because I felt like making it prettier and users reported issues with Redmine 4.0 compatibility, so I decided to fix them but going forward I don't plan to maintain this repo very actively.

That being said, pull requests are always welcome with fixes and improvements.
