### ISSUE TITLE
The ui of view issue is mess up

### ISSUE THREAD

**Issue by gainskills** [mrliptontea/PurpleMine2#114]
Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.2.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.5
  Mercurial                      4.0
  Bazaar                         2.8.0
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_ckeditor               1.2.2
  redmine_issue_dynamic_edit     0.6.6
  redmine_lightbox2              0.5.0

OS: MAC OS 10.14.5
Browser: Chrome 74.0.3729.169 (Official Build) (64-bit)

1. login to the system with the user which belongs to the role without 'permission-> issue tracking->edit issues'
2. the UI of view issue is mess up
![20190529-105852](https://user-images.githubusercontent.com/1937472/58517794-c9471300-8200-11e9-9201-9c1e6ada9527.png)

Expectation:
The UI should be shown properly

**Comment by mrliptontea** [comment]
Hey,

Good find with the permissions!

I tracked down the issue to the [redmine_issue_dynamic_edit](https://github.com/Ilogeek/redmine_issue_dynamic_edit) plugin. I suggest you report an issue there.

In the meantime, you can follow the [customization guide](/mrliptontea/PurpleMine2#how-to-customize-it) and use the following variables:

```scss
$css-grid-layout: false;
$flexbox-layout: false;
```

and then `npm run build`.

The layout will still be broken but arguably less so.

**Comment by mrliptontea** [comment]
The issue with the plugin is caused by closing `</div>` which shouldn't be there.

When the user can edit the issue, a `<div>` is inserted:
https://github.com/Ilogeek/redmine_issue_dynamic_edit/blob/0b2ba88f71f5c7f520ade158659d797b7c62eab8/lib/details_issue_hooks.rb#L47-L50

However, it's closed outside of that if:
https://github.com/Ilogeek/redmine_issue_dynamic_edit/blob/0b2ba88f71f5c7f520ade158659d797b7c62eab8/lib/details_issue_hooks.rb#L198
