### ISSUE TITLE
Long title in mobile not working correctly...

### ISSUE THREAD

**Issue by NormanEdance** [mrliptontea/PurpleMine2#117]
![image](https://user-images.githubusercontent.com/10945534/58876038-ce1f3180-86ee-11e9-94ba-7466f59b5a5f.png)

Hi guys!

**Comment by mrliptontea** [comment]
Hi,

I'm thinking this text is too bold and too big. Also, in older versions of Redmine, this was a regular select which means it would keep the text in one line and trim it, so this should work similarly because we don't want the header to expand and take up screen space.

Would this be enough?

![image](https://user-images.githubusercontent.com/3495587/58917511-c24b6380-871e-11e9-8be4-673236dde927.png)

**Comment by NormanEdance** [comment]
Yeah, I think it looks great. Thanks.
