### ISSUE TITLE
Something wrong with JSON script

### ISSUE THREAD

**Issue by yurmala** [mrliptontea/PurpleMine2#184]
Please see https://www.redmine.org/issues/30919

**Comment by mrliptontea** [comment]
Hi,

This theme does not include the default theme's application.css so it's not going to work that way. Also, because this is a patch, rather than a plugin, I'm not going to support it.

Instead, I recommend that you can follow the [customization steps](https://github.com/mrliptontea/PurpleMine2#how-to-customize-it), add the CSS from the patch yourself (e.g. create a new file `_group_custom_fields.scss` in `src/sass/`, include it in `application.scss`, and rebuild the theme.

**Comment by yurmala** [comment]
it's work. Good advice. Thank you!
