### ISSUE TITLE
Font family not defined 

### ISSUE THREAD

**Issue by Reeslo** [mrliptontea/PurpleMine2#20]
Example from time tracker plugin page, think font family "FontAwesome" was forget
![icons](https://cloud.githubusercontent.com/assets/2724844/11632349/f75cb372-9d06-11e5-91f3-fcf8167b2782.png)

![time-tracker](https://cloud.githubusercontent.com/assets/2724844/11632255/820a2cd0-9d06-11e5-985a-46ea32a4470f.png)

**Comment by mrliptontea** [comment]
Hi,

Which version of Time Tracker plugin do you use?
I recommend [hicknhack-software/redmine_time_tracker](https://github.com/hicknhack-software/redmine_time_tracker), it's still being developed and is supported by [PurpleMine](/mrliptontea/PurpleMine2#plugins).
The one you have doesn't work, because there is missing `icon` class, which applies font and some other basic styling for icons.

**Comment by mrliptontea** [comment]
Ah, sorry, my mistake - there are in fact missing icons in report. Fix is on the way!

**Comment by mrliptontea** [comment]
Fixed with 76fc0f4

**Comment by Reeslo** [comment]
I use the forked repository from hicknhack-software.

Thanks !
