### ISSUE TITLE
Do you accept contributions ?

### ISSUE THREAD

**Issue by dctremblay** [mrliptontea/PurpleMine2#53]
Hi @mrliptontea , at job we are switching for Redmine 2 to Redmine 3, and we decided also to implements a new theme, we choosed PurpleMine2.

A team of 7 peoples tested hard-way the theme on mobile phones, and reported many bugs.

If I do fix those bugs, would you accept the contributions that I will make ?

Thank you very much and have a great day !

**Comment by mrliptontea** [comment]
Hi,

Sure! Although I have not created contributions document, please keep in mind:

1. Make sure all your changes are backwards-compatible with Redmine 2.6+(while it's not officially supported anymore, there are still people who use 2.x, like yourself).
2. In SCSS, always use variables provided where applicable, for example for colours, padding sizes, etc. You can introduce new variables as needed.
3. I didn't set up any automatic checks on GitHub (it's on my list for a long time now), but make sure to check code using [scss-lint](https://github.com/brigade/scss-lint) for SCSS, and [standard](https://github.com/feross/standard) for JavaScript.
4. Because I don't want to force people to install Node.js on their Redmine servers, please do commit compiled application.css and theme.js as well as the source.

Please ask if you have further questions.

Thank you and happy coding!

**Comment by dctremblay** [comment]
@mrliptontea thanks for your great answer !

I have another question, I see that many of those bugs also present in the default theme provided stock with Redmine. Is PurpleMine2 extends the original Redmine source code ?

What I want to say is : Will I need to contribute both PurpleMine2 and Redmine for the fixes, or if I just contribute on the Redmine official default theme, it will affect also PurpleMine2 behavior ?

Thanks !

**Comment by mrliptontea** [comment]
PurpleMine is standalone, so you only need to modify PurpleMine. But yes, the first version was basically a rewrite of the default theme, which might explain why they share some issues.
