### ISSUE TITLE
Formatting issues after upgrading to PurpleMine2 v2.0

### ISSUE THREAD

**Issue by atc0005** [mrliptontea/PurpleMine2#90]
I upgraded this theme from from f5805c2 to 99ad2c5 on one of our Redmine instances (v4.0.2) today. After finding the issues noted below I reverted to v1.9.0 and came here to submit a bug report. 

- The trashcan icon for removing a user from the Watchers's list was forced down and off to the right (as if a hard return and a tab were visually applied)

![purplemine2_v2 0_upgrade_visual_oddities_watchers_list_remove_button](https://user-images.githubusercontent.com/36716992/54494767-d57f2d80-48ab-11e9-80f0-129f224590ea.png)

- The priority had a leading `=` sign

![purplemine2_v2 0_upgrade_visual_oddities_priority_level](https://user-images.githubusercontent.com/36716992/54494766-d57f2d80-48ab-11e9-8f1a-8c03d4dfdefa.png)

We have no plugins installed and have made no local modifications to Redmine.

On a different note, thank you very much for providing this theme; it has proven very popular with our team.

**Comment by mrliptontea** [comment]
Hi,

So as for the watchers' icon, this is indeed a bug/regression I accidentally introduced while adding support for Agile plugin. Please see 25ba736e7d5960c7221717508b04f8d2bfa7ec0f if it resolves it.

The equal sign though is there by design 😄 It's a priority icon for the default (medium) priority. Instead of highlighting the entire background in the list/issue page, icons are being used for improved accessibility - better contrasts and distinct shape for each priority. See this reference for Redmine's default priorities:
![priorities](https://user-images.githubusercontent.com/3495587/54499103-228fed80-4906-11e9-9902-92e3f65c504d.png)

**Comment by atc0005** [comment]
> The equal sign though is there by design 😄 It's a priority icon for the default (medium) priority. Instead of highlighting the entire background in the list/issue page, icons are being used for improved accessibility - better contrasts and distinct shape for each priority. See this reference for Redmine's default priorities:

Ah OK, I see what you mean. It looks pretty good in the overall issue list alongside tickets of other priorities.

> So as for the watchers' icon, this is indeed a bug/regression I accidentally introduced while adding support for Agile plugin. Please see [25ba736](https://github.com/mrliptontea/PurpleMine2/commit/25ba736e7d5960c7221717508b04f8d2bfa7ec0f) if it resolves it.

Tested and it appears to be fixed as of 25ba736. Thanks for the quick response!

**Comment by yurmala** [comment]
is it possible to make simple priority style?
![image](https://user-images.githubusercontent.com/9638475/79687278-e0468780-824e-11ea-9638-d1d9025ebe1c.png)
