### ISSUE TITLE
Agile chart endlessly expanding

### ISSUE THREAD

**Issue by pbystrov** [mrliptontea/PurpleMine2#93]
Hello,

We have Agile PRO plugin v1.4.8 and PurpleMine2 v2.0.1 installed and getting endlessly expanding Agile chart if we open it from Agile board.

Chart is opening fine in other themes.

![inspector view](https://i.snag.gy/TDapwC.jpg)

## Details:
```
Environment:
  Redmine version                4.0.0.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  additionals                    2.0.20
  clipboard_image_paste          1.13
  redmine_agile                  1.4.8
  redmine_checklists             3.1.14
  redmine_favorite_projects      2.0.3
  redmine_percent_done           1.1.0
  redmine_theme_changer          0.4.0
  redmineup_tags                 2.0.4
```

**Comment by mrliptontea** [comment]
I'm trying to replicate this but I can't, the chart has fixed height of 400px. Any idea if this is only possible in the pro version? I don't know why would it be expanding.

Also, I noticed the footer ends up being on the right side but this is because the markup is different on the chart page.

**Comment by mrliptontea** [comment]
I pushed some improvements to master, see if that changes anything?
If not, can you also try building the theme with `$css-grid-layout: true`?

**Comment by pbystrov** [comment]
It looks like I found the root cause.
The issue is caused by [Additionals](https://github.com/alphanodes/additionals) plugin with **Add "Go to top" link** option enabled.
Once I disable it everything starts working as expected.

PS. Thanks for the great theme!

**Comment by mrliptontea** [comment]
What a weird bug!

So there's a number of issues and potential "fixes here". I decided to go with the simplest one, which is to hide the "Go to top" link.

I also replicated the issue with the default theme, but it doesn't expand by itself, only when you resize the window.

The real issue here is the broken markup which causes the link to be injected in the wrong place. The reason why the endless expanding occurs with PurpleMine is that `#main` has `position: relative` required for the sidebar toggle button, and that affects Chart.js' hidden iframe's dimensions, and that is used to calculate the size of the chart. Another fix I came up with was to apply `.chartjs-hidden-iframe { height: 100vh !important; }` which basically restores the desired behaviour of this element from the default theme and stops the chart from expanding on its own but the issue remains when resizing the window.

Please see `issue-93-agile-chart-endlessly-expanding` if you're happy with the fix.

**Comment by pbystrov** [comment]
Confirmed working, thanks a lot!
